# Generated by Django 4.2.2 on 2023-07-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_offer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image_url",
            field=models.ImageField(default="media/", max_length=2083, upload_to=""),
        ),
    ]
