# Generated by Django 4.2.2 on 2023-07-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_product_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image_url",
            field=models.ImageField(default="media/", upload_to="fruits/"),
        ),
    ]
